# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ceadams/trees

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ceadams/trees

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ceadams/trees/CMakeFiles /Users/ceadams/trees//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ceadams/trees/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named trees.exe

# Build rule for target.
trees.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 trees.exe
.PHONY : trees.exe

# fast build rule for target.
trees.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/build
.PHONY : trees.exe/fast

#=============================================================================
# Target rules for targets named DUET

# Build rule for target.
DUET: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DUET
.PHONY : DUET

# fast build rule for target.
DUET/fast:
	$(MAKE) $(MAKESILENT) -f ModularDUET/CMakeFiles/DUET.dir/build.make ModularDUET/CMakeFiles/DUET.dir/build
.PHONY : DUET/fast

define_variables.o: define_variables.F90.o
.PHONY : define_variables.o

# target to build an object file
define_variables.F90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/define_variables.F90.o
.PHONY : define_variables.F90.o

define_variables.i: define_variables.F90.i
.PHONY : define_variables.i

# target to preprocess a source file
define_variables.F90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/define_variables.F90.i
.PHONY : define_variables.F90.i

define_variables.s: define_variables.F90.s
.PHONY : define_variables.s

# target to generate assembly for a file
define_variables.F90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/define_variables.F90.s
.PHONY : define_variables.F90.s

distribution.o: distribution.F90.o
.PHONY : distribution.o

# target to build an object file
distribution.F90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/distribution.F90.o
.PHONY : distribution.F90.o

distribution.i: distribution.F90.i
.PHONY : distribution.i

# target to preprocess a source file
distribution.F90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/distribution.F90.i
.PHONY : distribution.F90.i

distribution.s: distribution.F90.s
.PHONY : distribution.s

# target to generate assembly for a file
distribution.F90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/distribution.F90.s
.PHONY : distribution.F90.s

fuel_read.o: fuel_read.F90.o
.PHONY : fuel_read.o

# target to build an object file
fuel_read.F90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/fuel_read.F90.o
.PHONY : fuel_read.F90.o

fuel_read.i: fuel_read.F90.i
.PHONY : fuel_read.i

# target to preprocess a source file
fuel_read.F90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/fuel_read.F90.i
.PHONY : fuel_read.F90.i

fuel_read.s: fuel_read.F90.s
.PHONY : fuel_read.s

# target to generate assembly for a file
fuel_read.F90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/fuel_read.F90.s
.PHONY : fuel_read.F90.s

fuels_create.o: fuels_create.F90.o
.PHONY : fuels_create.o

# target to build an object file
fuels_create.F90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/fuels_create.F90.o
.PHONY : fuels_create.F90.o

fuels_create.i: fuels_create.F90.i
.PHONY : fuels_create.i

# target to preprocess a source file
fuels_create.F90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/fuels_create.F90.i
.PHONY : fuels_create.F90.i

fuels_create.s: fuels_create.F90.s
.PHONY : fuels_create.s

# target to generate assembly for a file
fuels_create.F90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/fuels_create.F90.s
.PHONY : fuels_create.F90.s

io.o: io.F90.o
.PHONY : io.o

# target to build an object file
io.F90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/io.F90.o
.PHONY : io.F90.o

io.i: io.F90.i
.PHONY : io.i

# target to preprocess a source file
io.F90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/io.F90.i
.PHONY : io.F90.i

io.s: io.F90.s
.PHONY : io.s

# target to generate assembly for a file
io.F90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/io.F90.s
.PHONY : io.F90.s

main.o: main.F90.o
.PHONY : main.o

# target to build an object file
main.F90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/main.F90.o
.PHONY : main.F90.o

main.i: main.F90.i
.PHONY : main.i

# target to preprocess a source file
main.F90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/main.F90.i
.PHONY : main.F90.i

main.s: main.F90.s
.PHONY : main.s

# target to generate assembly for a file
main.F90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/main.F90.s
.PHONY : main.F90.s

metryc.o: metryc.F90.o
.PHONY : metryc.o

# target to build an object file
metryc.F90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/metryc.F90.o
.PHONY : metryc.F90.o

metryc.i: metryc.F90.i
.PHONY : metryc.i

# target to preprocess a source file
metryc.F90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/metryc.F90.i
.PHONY : metryc.F90.i

metryc.s: metryc.F90.s
.PHONY : metryc.s

# target to generate assembly for a file
metryc.F90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/metryc.F90.s
.PHONY : metryc.F90.s

power_parser.o: power_parser.F90.o
.PHONY : power_parser.o

# target to build an object file
power_parser.F90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/power_parser.F90.o
.PHONY : power_parser.F90.o

power_parser.i: power_parser.F90.i
.PHONY : power_parser.i

# target to preprocess a source file
power_parser.F90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/power_parser.F90.i
.PHONY : power_parser.F90.i

power_parser.s: power_parser.F90.s
.PHONY : power_parser.s

# target to generate assembly for a file
power_parser.F90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/power_parser.F90.s
.PHONY : power_parser.F90.s

shapes.o: shapes.F90.o
.PHONY : shapes.o

# target to build an object file
shapes.F90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/shapes.F90.o
.PHONY : shapes.F90.o

shapes.i: shapes.F90.i
.PHONY : shapes.i

# target to preprocess a source file
shapes.F90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/shapes.F90.i
.PHONY : shapes.F90.i

shapes.s: shapes.F90.s
.PHONY : shapes.s

# target to generate assembly for a file
shapes.F90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/shapes.F90.s
.PHONY : shapes.F90.s

trees_read.o: trees_read.F90.o
.PHONY : trees_read.o

# target to build an object file
trees_read.F90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/trees_read.F90.o
.PHONY : trees_read.F90.o

trees_read.i: trees_read.F90.i
.PHONY : trees_read.i

# target to preprocess a source file
trees_read.F90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/trees_read.F90.i
.PHONY : trees_read.F90.i

trees_read.s: trees_read.F90.s
.PHONY : trees_read.s

# target to generate assembly for a file
trees_read.F90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/trees_read.F90.s
.PHONY : trees_read.F90.s

variables.o: variables.F90.o
.PHONY : variables.o

# target to build an object file
variables.F90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/variables.F90.o
.PHONY : variables.F90.o

variables.i: variables.F90.i
.PHONY : variables.i

# target to preprocess a source file
variables.F90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/variables.F90.i
.PHONY : variables.F90.i

variables.s: variables.F90.s
.PHONY : variables.s

# target to generate assembly for a file
variables.F90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.exe.dir/build.make CMakeFiles/trees.exe.dir/variables.F90.s
.PHONY : variables.F90.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DUET"
	@echo "... trees.exe"
	@echo "... define_variables.o"
	@echo "... define_variables.i"
	@echo "... define_variables.s"
	@echo "... distribution.o"
	@echo "... distribution.i"
	@echo "... distribution.s"
	@echo "... fuel_read.o"
	@echo "... fuel_read.i"
	@echo "... fuel_read.s"
	@echo "... fuels_create.o"
	@echo "... fuels_create.i"
	@echo "... fuels_create.s"
	@echo "... io.o"
	@echo "... io.i"
	@echo "... io.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... metryc.o"
	@echo "... metryc.i"
	@echo "... metryc.s"
	@echo "... power_parser.o"
	@echo "... power_parser.i"
	@echo "... power_parser.s"
	@echo "... shapes.o"
	@echo "... shapes.i"
	@echo "... shapes.s"
	@echo "... trees_read.o"
	@echo "... trees_read.i"
	@echo "... trees_read.s"
	@echo "... variables.o"
	@echo "... variables.i"
	@echo "... variables.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

